"""Parse the CWA Intermediate HTML and emit data/cwops-intermediate.js.

The source HTML uses Microsoft Office's "save as web" output, which is full of
<o:p>, mso-* style attributes, and stray &nbsp; runs. We clean those out while
preserving headings, paragraphs, lists, and hyperlinks.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "_sources" / "cwops-int.htm"
AUDIO_MAP = ROOT / "_sources" / "cwops-practice-audio.json"
OUT = ROOT / "data" / "cwops-intermediate.js"


# In-prose codes the curriculum uses to reference practice files. Each pattern
# captures a code that can be looked up (after normalization) in the audio map
# generated by extract_practice_audio.py.
CODE_PATTERN = re.compile(
    r"\b("
    r"WD\d+-\d+"
    r"|PR\d+-\d+"
    r"|SS\d+-\d+"
    r"|POTA\d+-\d+"
    r"|CWT[-\s]?\d+[-\s]?\d+"
    r"|QSO_?\d+-\d+"
    r"|(?:DIS|UN|IM|IN|RE|IR|ING|ES|ED|LY)\d+-\d+"
    r")\b",
    re.I,
)


def load_audio_map() -> dict[str, str]:
    if not AUDIO_MAP.exists():
        return {}
    return json.loads(AUDIO_MAP.read_text())


def lookup_audio(code: str, audio: dict[str, str]) -> str | None:
    """Try a few normalization variants to find the audio URL for a code."""
    # Replace whitespace with hyphen and uppercase.
    base = re.sub(r"\s+", "-", code).upper()
    candidates = [base]
    # Insert a hyphen between an alphabetic prefix and a digit run if missing.
    m = re.match(r"^([A-Z]+)(\d+.*)$", base)
    if m and not base.startswith(m.group(1) + "-"):
        candidates.append(f"{m.group(1)}-{m.group(2)}")
    # Underscore→hyphen variant of the above.
    candidates.extend(c.replace("_", "-") for c in list(candidates))
    # Hyphen→underscore between alpha and digits (some codes mix).
    for c in list(candidates):
        candidates.append(c.replace("-", "_"))
    # De-dup preserving order.
    seen, ordered = set(), []
    for c in candidates:
        if c not in seen:
            ordered.append(c)
            seen.add(c)
    for c in ordered:
        if c in audio:
            return audio[c]
    return None


def linkify_audio_codes(html: str, audio: dict[str, str]) -> tuple[str, list[dict]]:
    """Wrap practice-file codes in clickable mp3 links and collect them as tools."""
    found: list[dict] = []
    seen_keys: set[str] = set()

    def replace(m):
        code = m.group(1)
        url = lookup_audio(code, audio)
        if not url:
            return code
        key = (code.upper().replace(" ", "-"), url)
        if key not in seen_keys:
            seen_keys.add(key)
            found.append({"name": code, "url": url})
        return f'<a class="audio" href="{url}" target="_blank" rel="noopener">{code}</a>'

    # Avoid replacing inside existing <a>...</a> by splitting on tag boundaries.
    parts = re.split(r"(<a\b[^>]*>.*?</a>)", html, flags=re.S | re.I)
    for i, p in enumerate(parts):
        if i % 2 == 0:  # outside <a>
            parts[i] = CODE_PATTERN.sub(replace, p)
    return "".join(parts), found


def add_target_blank(html: str) -> str:
    """Ensure all <a href> tags in the rendered prose open in a new tab."""
    def fix(m):
        tag = m.group(0)
        if "target=" in tag.lower():
            return tag
        return tag[:-1] + ' target="_blank" rel="noopener">'
    return re.sub(r"<a\b[^>]*>", fix, html, flags=re.I)


# Speed range per session (from the document narrative).
SPEED_RANGE = {
    1: "10–13 WPM",
    2: "10–13 WPM",
    3: "10–13 WPM",
    4: "13–15 WPM",
    5: "13–15 WPM",
    6: "13–15 WPM",
    7: "15 WPM",
    8: "15 WPM",
    9: "15 WPM",
    10: "15 WPM",
    11: "18 WPM",
    12: "18 WPM",
    13: "18 WPM",
    14: "20 WPM",
    15: "20 WPM",
    16: "25 WPM (taste)",
}

SESSION_SUMMARY = {
    1: "Foundations. Establish the daily routine: Scales warm-up, ICR, callsign practice.",
    2: "Continue building the daily habit. More words and prefix copying at 10–13 WPM.",
    3: "Close out the introductory week. Add suffix files and longer LCWO sessions.",
    4: "Bump target to 13–15 WPM. Word/prefix/suffix files at the new speed.",
    5: "Lock in 13–15 WPM. Longer Morse Runner runs, more head-copy practice.",
    6: "Close the second speed bracket. Mixed exercises across all daily categories.",
    7: "Stabilize at 15 WPM. Short Story head copy practice is introduced.",
    8: "Continue 15 WPM. More short stories; deepen ICR habit.",
    9: "Sustain 15 WPM. QSO and POTA exchange practice in addition to drills.",
    10: "Final week at 15 WPM before the next bump. Polish all daily categories.",
    11: "Step up to 18 WPM. CWT (Morse Code Test) practice files introduced.",
    12: "Hold 18 WPM. WPX competition mode in Morse Runner.",
    13: "Close the 18 WPM bracket. Mix of CWT files and head-copy practice.",
    14: "Push to 20 WPM. Live CWT monitoring begins.",
    15: "Sustain 20 WPM with live CWT participation exercises.",
    16: "Capstone. Sample 25 WPM and attempt live CWT QSOs.",
}


def load_html() -> str:
    raw = SRC.read_text(encoding="utf-8", errors="replace")
    # Strip script and style blocks.
    raw = re.sub(r"<script\b.*?</script>", "", raw, flags=re.S | re.I)
    raw = re.sub(r"<style\b.*?</style>", "", raw, flags=re.S | re.I)
    return raw


def clean_inline(html: str) -> str:
    """Strip MS Office cruft from a fragment but keep <a>, <p>, <ul>, <ol>, <li>, <strong>, <em>."""
    s = html
    # Drop <o:p>, <o:smarttagtype>, etc.
    s = re.sub(r"</?o:[^>]+>", "", s, flags=re.I)
    s = re.sub(r"</?st1:[^>]+>", "", s, flags=re.I)
    # Drop spans/fonts entirely (keep the inner text).
    s = re.sub(r"</?(span|font|b|i|u)\b[^>]*>", "", s, flags=re.I)
    # Drop style/class attributes everywhere.
    s = re.sub(r"\s+(style|class|lang|align|valign|width|height|border|cellpadding|cellspacing)=\"[^\"]*\"", "", s, flags=re.I)
    s = re.sub(r"\s+(style|class|lang|align|valign|width|height|border|cellpadding|cellspacing)='[^']*'", "", s, flags=re.I)
    # Replace nbsp with normal space.
    s = s.replace("&nbsp;", " ").replace("&#160;", " ")
    # Normalize curly quotes the source uses so JSON-encoding doesn't break.
    s = (s.replace("‘", "'").replace("’", "'")
           .replace("“", '"').replace("”", '"')
           .replace("–", "–").replace("—", "—"))
    # Collapse stray whitespace inside tags.
    s = re.sub(r"<a\s+", "<a ", s, flags=re.I)
    # Strip target/rel/onclick attrs we'll add ourselves.
    s = re.sub(r"\s+(target|rel|onclick|name|id)=\"[^\"]*\"", "", s, flags=re.I)
    # Drop empty paragraphs.
    s = re.sub(r"<p>\s*</p>", "", s, flags=re.I)
    # Tags that snuck through that we don't want — strip but keep contents.
    for t in ["div"]:
        s = re.sub(rf"</?{t}\b[^>]*>", "", s, flags=re.I)
    # Collapse runs of whitespace inside text.
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r">\s+<", "><", s)
    # Re-introduce a space between adjacent inline elements where it helps readability.
    return s.strip()


def extract_links(fragment: str) -> list[dict]:
    out = []
    seen = set()
    for m in re.finditer(r"<a[^>]*href=\"([^\"]+)\"[^>]*>(.*?)</a>", fragment, flags=re.S | re.I):
        url = m.group(1).strip()
        text = re.sub(r"<[^>]+>", "", m.group(2)).strip()
        text = re.sub(r"\s+", " ", text)
        key = (url, text.lower())
        if key in seen:
            continue
        seen.add(key)
        out.append({"name": text or url, "url": url})
    return out


def split_paragraphs(fragment: str) -> str:
    """Wrap fragment so it renders as a series of paragraphs.

    The source uses bare <p> elements but the cleaning pass above can leave us
    with floating text and inline runs. We split on closing </p>, drop empties,
    and reassemble.
    """
    parts = re.split(r"</p>", fragment, flags=re.I)
    cleaned = []
    for part in parts:
        # Strip opening <p ...> if present.
        part = re.sub(r"^\s*<p\b[^>]*>", "", part, flags=re.I).strip()
        # Strip leftover stray closing tags.
        part = re.sub(r"^\s*<br\b[^>]*/?>", "", part, flags=re.I).strip()
        if not part:
            continue
        # Skip if it's only punctuation or a single non-breaking space.
        text_only = re.sub(r"<[^>]+>", "", part).strip()
        if not text_only:
            continue
        cleaned.append(f"<p>{part}</p>")
    return "\n".join(cleaned)


def slice_between(html: str, start: int, end: int | None) -> str:
    return html[start:end] if end is not None else html[start:]


def find_h_offsets(html: str, level: str) -> list[tuple[int, str, int]]:
    """Return (start_offset, inner_text, end_offset) for every <hN> in the document."""
    out = []
    for m in re.finditer(rf"<{level}[^>]*>(.*?)</{level}>", html, flags=re.S | re.I):
        inner = re.sub(r"<[^>]+>", "", m.group(1)).strip()
        inner = re.sub(r"\s+", " ", inner)
        out.append((m.start(), inner, m.end()))
    return out


def parse_sessions(html: str, audio: dict[str, str]) -> list[dict]:
    """Walk the document, find all 48 'Day' H3s, group every 3 into a session."""
    day_h3s = [
        (start, end) for start, txt, end in find_h_offsets(html, "h3") if re.match(r"day\s+(one|two|three)", txt, re.I)
    ]
    assert len(day_h3s) == 48, f"Expected 48 Day H3s, got {len(day_h3s)}"

    sessions = []
    for session_idx in range(16):
        session_id = session_idx + 1
        days = []
        for d in range(3):
            day_idx = session_idx * 3 + d
            day_start, day_inner_end = day_h3s[day_idx]
            # End of this day's content = start of next day's H3 (or end of doc).
            if day_idx + 1 < len(day_h3s):
                day_end = day_h3s[day_idx + 1][0]
            else:
                # Stop at the Appendix or Revision History — whichever comes
                # first. The h1 markup has nested anchors so we anchor on
                # the heading text directly.
                tail = html[day_inner_end:]
                candidates = [m.start() for m in (
                    re.search(r"Appendix\s+A:", tail),
                    re.search(r"Document Revision History", tail, re.I),
                ) if m]
                day_end = day_inner_end + min(candidates) if candidates else len(html)
                # Walk back to the nearest opening <h1 to leave a clean cut.
                back = html.rfind("<h1", day_inner_end, day_end)
                if back != -1:
                    day_end = back
            day_html = slice_between(html, day_inner_end, day_end)
            day_html = clean_inline(day_html)
            day_html = split_paragraphs(day_html)

            # First, collect the page-level/tool links the source already provides.
            ref_tools = extract_links(day_html)
            # Then, find practice-file codes in the prose and turn them into
            # direct mp3 links. These also get added to the day's tools list.
            day_html, audio_tools = linkify_audio_codes(day_html, audio)
            day_html = add_target_blank(day_html)

            # Merge tools, deduping by URL.
            seen, tools = set(), []
            for t in ref_tools + audio_tools:
                if t["url"] in seen:
                    continue
                seen.add(t["url"])
                tools.append(t)

            days.append(
                {
                    "label": f"Day {d + 1}",
                    "bodyHtml": day_html,
                    "tools": tools,
                }
            )
        sessions.append(
            {
                "id": session_id,
                "title": f"Session {session_id} · {SPEED_RANGE[session_id]}",
                "summary": SESSION_SUMMARY[session_id],
                "speedRange": SPEED_RANGE[session_id],
                "days": days,
            }
        )
    return sessions


def parse_intro_and_tools(html: str) -> dict:
    """Extract the document's Introduction and Tools for This Course sections."""
    body_start_m = re.search(r"<body[^>]*>", html, flags=re.I)
    body_start = body_start_m.end() if body_start_m else 0
    # Locate the Introduction H1
    intro_m = re.search(r"<h1[^>]*>\s*Introduction\s*</h1>", html[body_start:], flags=re.I)
    tools_m = re.search(r"<h1[^>]*>\s*Tools for This Course\s*</h1>", html[body_start:], flags=re.I)
    sess_m = re.search(r"<h1[^>]*>\s*Assignments\s*</h1>", html[body_start:], flags=re.I)
    if not (intro_m and tools_m):
        return {"introHtml": "", "toolsHtml": ""}

    intro_start = body_start + intro_m.end()
    intro_end = body_start + tools_m.start()
    tools_start = body_start + tools_m.end()
    if sess_m:
        tools_end = body_start + sess_m.start()
    else:
        # Fallback: stop at first Session H2.
        s2 = re.search(r"<h2[^>]*>\s*Session", html[tools_start:], flags=re.I)
        tools_end = tools_start + s2.start() if s2 else len(html)

    intro_html = clean_inline(html[intro_start:intro_end])
    intro_html = split_paragraphs(intro_html)
    tools_html = clean_inline(html[tools_start:tools_end])
    tools_html = split_paragraphs(tools_html)
    return {"introHtml": intro_html, "toolsHtml": tools_html}


def js_string(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def emit(sessions: list[dict], parts: dict) -> str:
    out = []
    out.append("// Auto-generated by _sources/build_cwops_data.py — do not edit by hand.")
    out.append("// Re-run the script after updating _sources/cwops-int.htm.")
    out.append("")
    out.append("export default {")
    out.append('  id: "cwops-intermediate",')
    out.append('  shortName: "CWA Intermediate",')
    out.append('  longName: "CW Academy Intermediate Curriculum (v2.2)",')
    out.append('  subtitle: "16 sessions · 10→25 WPM",')
    out.append('  description: "CW Academy\'s Intermediate course. Sixteen sessions over eight weeks, building from 10 WPM through 25 WPM with daily LCWO ICR, Morse Runner callsign practice, QSO/POTA exchanges, and CWT events.",')
    out.append('  source: {')
    out.append('    org: "CW Academy / CWops",')
    out.append('    pdfUrl: "https://cwa.cwops.org/wp-content/uploads/Practice-Instructions-Intermediate-ver.2.2.pdf",')
    out.append('    referenceUrl: "https://cwa.cwops.org/wp-content/uploads/Practice-Instructions-Intermediate-ver.2.2.htm",')
    out.append('  },')
    out.append('  intro: {')
    out.append('    title: "About the Intermediate Course",')
    out.append('    sections: [')
    out.append('      {')
    out.append('        heading: "Introduction",')
    out.append(f"        html: {js_string(parts['introHtml'])},")
    out.append('      },')
    out.append('      {')
    out.append('        heading: "Tools for This Course",')
    out.append(f"        html: {js_string(parts['toolsHtml'])},")
    out.append('      },')
    out.append('    ],')
    out.append('  },')
    out.append('  assessment: null,')
    out.append('  lessons: [')
    for s in sessions:
        out.append("    {")
        out.append(f"      id: {s['id']},")
        out.append(f"      title: {js_string(s['title'])},")
        out.append(f"      summary: {js_string(s['summary'])},")
        out.append(f"      speedRange: {js_string(s['speedRange'])},")
        out.append("      days: [")
        for d in s["days"]:
            out.append("        {")
            out.append(f"          label: {js_string(d['label'])},")
            out.append(f"          bodyHtml: {js_string(d['bodyHtml'])},")
            out.append("          tools: [")
            for t in d["tools"]:
                out.append("            {")
                out.append(f"              name: {js_string(t['name'])},")
                out.append(f"              url: {js_string(t['url'])},")
                out.append("            },")
            out.append("          ],")
            out.append("        },")
        out.append("      ],")
        out.append("    },")
    out.append("  ],")
    out.append("};")
    out.append("")
    return "\n".join(out)


def main():
    html = load_html()
    audio = load_audio_map()
    if not audio:
        print("WARNING: audio map missing — re-run extract_practice_audio.py first.")
    parts = parse_intro_and_tools(html)
    parts["introHtml"] = add_target_blank(parts["introHtml"])
    parts["toolsHtml"] = add_target_blank(parts["toolsHtml"])
    sessions = parse_sessions(html, audio)
    OUT.write_text(emit(sessions, parts), encoding="utf-8")
    n_links = sum(len(d["tools"]) for s in sessions for d in s["days"])
    n_audio = sum(1 for s in sessions for d in s["days"] for t in d["tools"] if ".mp3" in t["url"])
    print(f"Wrote {OUT}")
    print(f"  Sessions: {len(sessions)}")
    print(f"  Days:     {sum(len(s['days']) for s in sessions)}")
    print(f"  Tool links across all days: {n_links}")
    print(f"  Of those, audio (mp3) links: {n_audio}")


if __name__ == "__main__":
    main()
